package de.emp2020.alertManager;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


@Entity
public class Distance {
	
	
	@Id
	@GeneratedValue
	private int id;
	
	@Column(nullable=false)
	private String token;

	@Column(nullable=false)
	private double distance;
	
	private int priority = -1;
	
	
	
	@Override
	public boolean equals(Object obj) {
		if (obj == this)
		{
			return true;
		}
		if (obj.getClass() != this.getClass())
		{
			return false;
		}
		else
		{
			Distance dist = (Distance) obj;
			return dist.getToken().equals(this.getToken());
		}
	}
	
	
	// Autogenerated Getters and Setters
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public double getDistance() {
		return distance;
	}

	public void setDistance(double distance) {
		this.distance = distance;
	}

	public int getPriority() {
		return priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
