package de.emp2020.alertManager;

public class DistanceJson {
	
	private int alertId;
	private String userToken;
	private double distance;
	
	
	//Autogenerated Getters and Setters
	public int getAlertId() {
		return alertId;
	}
	public void setAlertId(int alertId) {
		this.alertId = alertId;
	}
	public String getUserToken() {
		return userToken;
	}
	public void setUserToken(String userToken) {
		this.userToken = userToken;
	}
	public double getDistance() {
		return distance;
	}
	public void setDistance(double distance) {
		this.distance = distance;
	}
	
	
	
}
